FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY .env ./.env
COPY batch_finish*.jsonl ./

CMD ["python", "-u", "src/ml_model_auto_retraining.py"]
